const Disclaimers = () => {
  return (
    <div id="Disclaimers" className="disclaimers container">
      <div className="content">
        <div className="section-header">
          <h3 className="sub-title">Disclaimers</h3>
        </div>
        <p>(***)Insigneo Securities, LLC ("IS") and Insigneo Advisory Services, LLC ("IAS") have approved <strong>Marcelo Borrelli</strong>, a representative of IS and IAS, to conduct his securities and advisory activities doing business as <strong>Borrelli Capital Management ("BCM")</strong> BCM is not itself a broker dealer or an investment advisor. Insigneo Financial Group, LLC comprises a number of operating businesses engaged in the offering of brokerage and advisory products and services in various jurisdictions, principally in Latin America. Brokerage products and services are offered through Insigneo International Financial Services, LLC, headquartered in Puerto Rico, and through Insigneo Securities, LLC, headquartered in Miami Both are members of the Financial Industry Regulatory Authority (FINRA) and Securities Investors Protection Corporation (SIPC). Investment advisory products and services are offered through Insigneo Advisory Services, LLC, an investment adviser registered with the Securities and Exchange Commission. In Uruguay, advisory services are offered through Insigneo International Asesores de Inversion Uruguay, SA, Insigneo Asesores de Inversion Latam, SRL, and Insigneo Asesores de Inversion de Uruguay, SRL, in Argentina through Insigneo Argentina, SAU, and in Chile through Insigneo Asesorias Financieras, SPA. Collectively, these eight operating businesses make up the Insigneo Financial Group. To learn more about the Broker Dealers including their conflicts of interest and compensation practices, please go to <a href="https://insigneo.com/disclosures/" target="_blank" rel="noreferrer">https://insigneo.com/disclosures/</a> or via <a href="https://www.finra.org/#/" target="_blank" rel="noreferrer">www.finra.org</a>. To learn about Insigneo Advisory Services, LLC and any conflicts related to its advisory services, please see its Form ADV and brochure which can be found at Investment Advisor Public Disclosure website <a href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fadviserinfo.sec.gov%2F&data=05%7C01%7Cmarcelo.borrelli%40insigneo.com%7Ccc878620fd8d45a1e4d608dac9798787%7Cc9ccb7c6f8624b95973a09ed9a63367a%7C0%7C0%7C638043821065201796%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IQ5fAIRd%2BnqSDFtiWOhp1gA%2BGn7QiCK6PLC%2B536kJXU%3D&reserved=0" target="_blank" rel="noreferrer">https://adviserinfo.sec.gov/</a>. Check the background of this investment professional on <a href="https://brokercheck.finra.org/" target="_blank" rel="noreferrer">https://brokercheck.finra.org/</a></p>
      </div>
    </div>
  )
}

export default Disclaimers;
